/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package baekjoon;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Arrays;

public class App {
    public static void main(String[] args) throws IOException {
        // p1001.main(args);
    }
}
